trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - src/scaffolders/power-platform/*

pool:
  vmImage: windows-latest

parameters:

  - name: adoAccountName
    displayName : The domain name of the Azure DevOps instance Name e.g. CapgeminiUk
    type: string
  - name: adoProjectName
    displayName : The name of the Project to scaffold onto within Azure DevOps
    type: string
  - name: customer
    displayName : The Name of the Customer excluding spaces e.g Customer
    type: string
  - name: customerProject
    displayName : The Name of the Customer Internal project or program name e.g RenovationProject
    type: string
  - name: serviceEndPointTenantId
    displayName : The TenantId (Guid) of where the tenant sits
    type: string
  - name: serviceEndPointClientId
    displayName : The ClientId / Application Id from the App Registration from Azure AD (Guid)
    type: string
  - name: serviceEndPointSecret
    displayName : The Secret for Client / Application Register App from Azure AD (Guid)
    type: string
  - name: serviceClientUrl
    displayName : The url of the extract environment to run the solution checker e.g https:\\org123.crm4.dynamics.com
    type: string
  - name: releaseEnvironments
    displayName : The comma seperated list of environments for releases e.g TST,PRE,PRD
    type: string

steps:
- checkout: self
  persistCredentials: true
  
- task: PowerShell@2
  displayName : 'Install Template'
  inputs:
    targetType: 'inline'
    script: 'dotnet new --install .'
    workingDirectory: '$(system.defaultworkingdirectory)/src/scaffolders/power-platform/PowerApps/template'

- task: PowerShell@2
  displayName : 'Create Scaffold temporary directory'
  inputs:
    targetType: 'inline'
    script: 'mkdir ScaffoldTemp'
    workingDirectory: '$(system.defaultworkingdirectory)'

- task: PowerShell@2
  displayName : 'Run Scaffold from temp directory'
  inputs:
    targetType: 'inline'
    script: 'dotnet new Capgemini.PowerApps.Scaffolder -n ${{ parameters.customer}}.${{ parameters.customerProject }} --patToken $(PATToken) --repositoryName ${{ parameters.customer}}.${{ parameters.customerProject }} --adoAccountName ${{ parameters.adoAccountName}} --adoProjectName ${{ parameters.adoProjectName}} --serviceEndPointClientId ${{ parameters.serviceEndPointClientId }} --serviceEndPointSecret ${{ parameters.serviceEndPointSecret }} --serviceClientUrl ${{ parameters.serviceClientUrl }} --serviceEndPointTenantId ${{ parameters.serviceEndPointTenantId }} --allow-scripts yes'
    pwsh: true
    workingDirectory: '$(system.defaultworkingdirectory)/ScaffoldTemp'
    runScriptInSeparateScope: true