$AdoAccountName = "__adoAccountName__"
$ProjectName = "__adoProjectName__"
$AdoToken = "__patToken__"

$orgUrl = "https://dev.azure.com/$AdoAccountName"

$env:AZURE_DEVOPS_EXT_PAT = $AdoToken

$existingProject = az devops project show --project $ProjectName --org $orgUrl

if($null -eq $existingProject)
{
	Write-Host "Project $ProjectName must exist"
	return -1
}

Write-Host "Create git repo and push to ADO"

git config --global user.email "agent@scaffold.com"
git config --global user.name "buildService"


git init .
git checkout -b dev
git add --all
git commit -m "first version of code generated by power apps project scaffolder"

az repos create --name CDSRepo --project $ProjectName --org $orgUrl

git remote add origin https://__patToken__@dev.azure.com/__adoAccountName__/__adoProjectName__/_git/CDSRepo
git push -u origin --all

Write-Host "Create ADO pipelines"
az pipelines create --name '1 Company - PR' --folder-path 'PR' --description 'PR Pipeline for Project' --repository "$orgUrl/$ProjectName/_git/CDSRepo" --branch dev --yml-path "/pipelines/azure-pipelines-pull-request.yml" --project $ProjectName --org $orgUrl
az pipelines create --name '1 Company - Main' --folder-path 'CI' --description 'Pipeline for Project' --repository "$orgUrl/$ProjectName/_git/CDSRepo" --branch dev --yml-path "/pipelines/azure-pipelines.yml" --project $ProjectName --org $orgUrl

return 0

#TODO Scaffold Wiki Pages here 
