trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - src/azure-devops/Project/*

pool:
  vmImage: windows-latest

parameters:
  - name: ProjectName
    type: string
    default: CUSTOMER-PROJECT-NAME
  - name: AdoAccountName
    type: string
  - name: InheritedProcessName
    type: string
    default: Agile
  - name: Template
    type: string
    default: capgemini

steps:
- task: PowerShell@2
  inputs:
    filePath: $(system.defaultworkingdirectory)/src/scaffolders/azure-devops/Project/setup.ps1
    arguments: 
        -AdoAccountName ${{ parameters.AdoAccountName}} 
        -AdoToken $(PATToken)
        -InheritedProcessName ${{ parameters.InheritedProcessName}} 
        -ConfigurationType ${{ parameters.Template}}
        -ProjectName ${{ parameters.ProjectName}}
    
