name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - /src/infra/*

parameters:
  - name: deployFromFeature
    displayName: "Deploy to DEV?"
    type: boolean
    default: false

extends:
  template: /src/infra/shared/template.yaml
  parameters:
    templates:
      - path: src/infra/keyvault
        name: keyvault
        type: bicep
        scope: Resource Group
        resourceGroupName: '$(environment)-$(projectName)-$(nc_infrastructure)-$(nc_resourcegroup)-$(region)-01'
      - path: src/infra/appServicePlans
        name: functionASP
        type: bicep
        scope: Resource Group
        resourceGroupName: '$(environment)-$(projectName)-$(nc_infrastructure)-$(nc_resourcegroup)-$(region)-01'
    deployFromFeature: ${{ parameters.deployFromFeature }}